# Generated by Django 5.1 on 2024-08-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Law_Assistant', '0002_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
    ]
